/*
 * @Author: LIKE_A_STAR
 * @Date: 2024-02-28 11:13:52
 * @LastEditors: LIKE_A_STAR
 * @LastEditTime: 2024-03-02 15:10:02
 * @Description:
 * @FilePath: \vscode programd:\vscode\goWorker\src\douyin\hertz-server\main.go
 */
// Code generated by hertz generator.

package main

import (
	"douyin/hertz-server/pkg/kitex_client"
	"douyin/hertz-server/pkg/mq"
	"douyin/hertz-server/pkg/mw"
	"douyin/hertz-server/pkg/parse"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/gzip"
)

func main() {
	// parse.Init("./local.yaml")
	parse.Init("./config.yaml")

	mw.InitJwt()

	kitex_client.Init()

	mq.Init()
	mq.PublishSimple("favorite")
	mq.PublishSimple("follow")

	h := server.Default(
		server.WithHostPorts("0.0.0.0:8888"),
		server.WithMaxRequestBodySize(50*1024*1024),
	)

	h.Use(gzip.Gzip(gzip.BestCompression))

	register(h)
	h.Spin()
}
