// Code generated by Kitex v0.7.1. DO NOT EDIT.

package favoriteservice

import (
			"context"
				favorite_rpc "douyin/favorite-rpc/favorite_rpc"
				client "github.com/cloudwego/kitex/client"
				kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return favoriteServiceServiceInfo
 }

var favoriteServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "FavoriteService"
	handlerType := (*favorite_rpc.FavoriteService)(nil)
	methods := map[string]kitex.MethodInfo{
		"FavoriteAction":
			kitex.NewMethodInfo(favoriteActionHandler, newFavoriteServiceFavoriteActionArgs, newFavoriteServiceFavoriteActionResult, false),
		"IsFavorite":
			kitex.NewMethodInfo(isFavoriteHandler, newFavoriteServiceIsFavoriteArgs, newFavoriteServiceIsFavoriteResult, false),
		"FavoriteVideo":
			kitex.NewMethodInfo(favoriteVideoHandler, newFavoriteServiceFavoriteVideoArgs, newFavoriteServiceFavoriteVideoResult, false),
	}
	extra := map[string]interface{}{
		"PackageName":	 "favorite_rpc",
		"ServiceFilePath": "..\\idl\\kitex-idl\\favorite_rpc.thrift",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName: 	 serviceName,
		HandlerType: 	 handlerType,
		Methods:     	 methods,
		PayloadCodec:  	 kitex.Thrift,
		KiteXGenVersion: "v0.7.1",
		Extra:           extra,
	}
	return svcInfo
}



func favoriteActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error { 
	realArg := arg.(*favorite_rpc.FavoriteServiceFavoriteActionArgs)
	realResult := result.(*favorite_rpc.FavoriteServiceFavoriteActionResult)
	success, err := handler.(favorite_rpc.FavoriteService).FavoriteAction(ctx, realArg.Request)
	if err != nil {
	return err
	}
	realResult.Success = success
	return nil 
}
func newFavoriteServiceFavoriteActionArgs() interface{} {
	return favorite_rpc.NewFavoriteServiceFavoriteActionArgs()
}

func newFavoriteServiceFavoriteActionResult() interface{} {
	return favorite_rpc.NewFavoriteServiceFavoriteActionResult()
}


func isFavoriteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error { 
	realArg := arg.(*favorite_rpc.FavoriteServiceIsFavoriteArgs)
	realResult := result.(*favorite_rpc.FavoriteServiceIsFavoriteResult)
	success, err := handler.(favorite_rpc.FavoriteService).IsFavorite(ctx, realArg.Request)
	if err != nil {
	return err
	}
	realResult.Success = success
	return nil 
}
func newFavoriteServiceIsFavoriteArgs() interface{} {
	return favorite_rpc.NewFavoriteServiceIsFavoriteArgs()
}

func newFavoriteServiceIsFavoriteResult() interface{} {
	return favorite_rpc.NewFavoriteServiceIsFavoriteResult()
}


func favoriteVideoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error { 
	realArg := arg.(*favorite_rpc.FavoriteServiceFavoriteVideoArgs)
	realResult := result.(*favorite_rpc.FavoriteServiceFavoriteVideoResult)
	success, err := handler.(favorite_rpc.FavoriteService).FavoriteVideo(ctx, realArg.Request)
	if err != nil {
	return err
	}
	realResult.Success = success
	return nil 
}
func newFavoriteServiceFavoriteVideoArgs() interface{} {
	return favorite_rpc.NewFavoriteServiceFavoriteVideoArgs()
}

func newFavoriteServiceFavoriteVideoResult() interface{} {
	return favorite_rpc.NewFavoriteServiceFavoriteVideoResult()
}


type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}


func (p *kClient) FavoriteAction(ctx context.Context , request *favorite_rpc.FavoriteActionReq) (r *favorite_rpc.FavoriteActionResp, err error) {
	var _args favorite_rpc.FavoriteServiceFavoriteActionArgs
	_args.Request = request
	var _result favorite_rpc.FavoriteServiceFavoriteActionResult
	if err = p.c.Call(ctx, "FavoriteAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) IsFavorite(ctx context.Context , request *favorite_rpc.IsFavoriteReq) (r *favorite_rpc.IsFavoriteResp, err error) {
	var _args favorite_rpc.FavoriteServiceIsFavoriteArgs
	_args.Request = request
	var _result favorite_rpc.FavoriteServiceIsFavoriteResult
	if err = p.c.Call(ctx, "IsFavorite", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FavoriteVideo(ctx context.Context , request *favorite_rpc.FavoriteVideoReq) (r *favorite_rpc.FavoriteVideoResp, err error) {
	var _args favorite_rpc.FavoriteServiceFavoriteVideoArgs
	_args.Request = request
	var _result favorite_rpc.FavoriteServiceFavoriteVideoResult
	if err = p.c.Call(ctx, "FavoriteVideo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

