// Code generated by hertz generator.

package user_api

import (
	"context"

	user_api "douyin/app/biz/model/user_api"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Register .
// @router /douyin/user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user_api.RegisterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user_api.RegisterResp)

	c.JSON(consts.StatusOK, resp)
}

// Userinfo .
// @router /douyin/user [GET]
func Userinfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user_api.UserinfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user_api.UserinfoResp)

	c.JSON(consts.StatusOK, resp)
}

// Login .
// @router /douyin/user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user_api.LoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user_api.LoginResp)

	c.JSON(consts.StatusOK, resp)
}
