// Code generated by hertz generator.

package favorite_api

import (
	"context"

	favorite_api "douyin/internal/hertz-server/model/favorite_api"
	"douyin/internal/hertz-server/model/user_api"
	"douyin/internal/hertz-server/model/video_api"
	"douyin/internal/pkg/kitex_client"
	"douyin/internal/pkg/mw"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// FavoriteAction .
// @router /douyin/favorite/action [POST]
func FavoriteAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req favorite_api.FavoriteActionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(favorite_api.FavoriteActionResp)

	// 获取用户id
	rowUserID, ok := c.Get("user_id")
	if !ok {
		resp.StatusCode = 1
		resp.StatusMsg = "could not find user_id"
		c.JSON(consts.StatusOK, resp)
		return
	}
	userID := rowUserID.(int64)

	// 查看视频所对应的用户的id
	videoList, err := kitex_client.VideoInfoRpc(ctx, []int64{req.VideoID})
	if err != nil {
		resp.StatusCode = 1
		resp.StatusMsg = err.Error()
		c.JSON(consts.StatusOK, resp)
		return
	}

	switch req.ActionType {
	case 1: // 点赞视频
		// 创建相关用户点赞信息字段
		if err := kitex_client.FavoriteActionRpc(ctx, kitex_client.IncFavorite, userID, req.VideoID); err != nil {
			resp.StatusCode = 1
			resp.StatusMsg = err.Error()
			c.JSON(consts.StatusOK, resp)
			return
		}

		// 用户点赞数和被点赞的用户的获赞数自增
		if err := kitex_client.UserInfoActionRpc(ctx, kitex_client.IncUserFavorite, userID, &videoList.Videos[0].UserId); err != nil {
			resp.StatusCode = 1
			resp.StatusMsg = err.Error()
			c.JSON(consts.StatusOK, resp)
			return
		}

		// 被点赞的作品的获赞数自增
		if err := kitex_client.VideoInfoActionRpc(ctx, kitex_client.IncVideoFavorite, req.VideoID); err != nil {
			resp.StatusCode = 1
			resp.StatusMsg = err.Error()
			c.JSON(consts.StatusOK, resp)
			return
		}
	case 2: // 取消点赞
		// 删除相关用户点赞信息字段
		if err := kitex_client.FavoriteActionRpc(ctx, kitex_client.DecFavorite, userID, req.VideoID); err != nil {
			resp.StatusCode = 1
			resp.StatusMsg = err.Error()
			c.JSON(consts.StatusOK, resp)
			return
		}

		// 用户点赞数和被点赞的用户的获赞数自减
		if err := kitex_client.UserInfoActionRpc(ctx, kitex_client.DecUserFavorite, userID, &videoList.Videos[0].UserId); err != nil {
			resp.StatusCode = 1
			resp.StatusMsg = err.Error()
			c.JSON(consts.StatusOK, resp)
			return
		}

		// 被点赞的作品的获赞数自减
		if err := kitex_client.VideoInfoActionRpc(ctx, kitex_client.DecVideoFavorite, req.VideoID); err != nil {
			resp.StatusCode = 1
			resp.StatusMsg = err.Error()
			c.JSON(consts.StatusOK, resp)
			return
		}
	default:
		resp.StatusCode = 1
		resp.StatusMsg = "Invalid action type"
		c.JSON(consts.StatusOK, resp)
		return
	}

	resp.StatusCode = 0
	resp.StatusMsg = "OK"
	c.JSON(consts.StatusOK, resp)
}

// FavoriteList .
// @router /douyin/favorite/list [GET]
func FavoriteList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req favorite_api.FavoriteListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(favorite_api.FavoriteListResp)

	// 获取用户点赞的视频id列表
	favoriteVideoRpc, err := kitex_client.FavoriteVideoRpc(ctx, req.UserID)
	if err != nil {
		resp.StatusCode = 1
		resp.StatusMsg = err.Error()
		c.JSON(consts.StatusOK, resp)
		return
	}
	align := len(favoriteVideoRpc.VideoId)

	// 通过视频id查看视频相关信息
	videoListRpc, err := kitex_client.VideoInfoRpc(ctx, favoriteVideoRpc.VideoId)
	if err != nil {
		resp.StatusCode = 1
		resp.StatusMsg = err.Error()
		c.JSON(consts.StatusOK, resp)
		return
	}
	if align != len(videoListRpc.Videos) {
		resp.StatusCode = 1
		resp.StatusMsg = "invalid align video list"
		c.JSON(consts.StatusOK, resp)
		return
	}

	// 查看视频对应的用户的信息
	ownerIDList := make([]int64, 0, align)
	for _, v := range videoListRpc.Videos {
		ownerIDList = append(ownerIDList, v.UserId)
	}
	userListRpc, err := kitex_client.UserListRpc(ctx, ownerIDList)
	if err != nil {
		resp.StatusCode = 1
		resp.StatusMsg = err.Error()
		c.JSON(consts.StatusOK, resp)
		return
	}

	// 查看视频是否点赞 用户是否关注
	var isFollowList []bool
	var isFavoriteList []bool
	if req.Token == nil || *req.Token == "" { // nil对应不存在token字段，""对应token值为空
		isFollowList = make([]bool, 0, align)
		isFavoriteList = make([]bool, 0, align)
		for i := 0; i < align; i++ {
			isFollowList = append(isFollowList, false)
			isFavoriteList = append(isFavoriteList, false)
		}
	} else {
		userID, err := mw.TokenGetUserId(req.Token)
		if err != nil {
			resp.StatusCode = 1
			resp.StatusMsg = err.Error()
			c.JSON(consts.StatusOK, resp)
			return
		}

		isFollowRpc, err := kitex_client.IsFollowRpc(ctx, userID, ownerIDList)
		if err != nil {
			resp.StatusCode = 1
			resp.StatusMsg = err.Error()
			c.JSON(consts.StatusOK, resp)
			return
		}
		if align != len(isFollowRpc.IsFollow) {
			resp.StatusCode = 1
			resp.StatusMsg = "invalid align follow list"
			c.JSON(consts.StatusOK, resp)
			return
		}
		isFollowList = isFollowRpc.IsFollow

		isFavoriteRpc, err := kitex_client.IsFavoriteRpc(ctx, userID, favoriteVideoRpc.VideoId)
		if err != nil {
			resp.StatusCode = 1
			resp.StatusMsg = err.Error()
			c.JSON(consts.StatusOK, resp)
			return
		}
		if align != len(isFavoriteRpc.IsFavorite) {
			resp.StatusCode = 1
			resp.StatusMsg = "invalid align favorite list"
			c.JSON(consts.StatusOK, resp)
			return
		}
		isFavoriteList = isFavoriteRpc.IsFavorite
	}

	for i := 0; i < align; i++ {
		resp.VideoList = append(resp.VideoList, &video_api.Video{
			ID: videoListRpc.Videos[i].Id,
			Author: &user_api.User{
				ID:              userListRpc.Users[i].Id,
				Name:            userListRpc.Users[i].Name,
				FollowCount:     userListRpc.Users[i].FollowCount,
				FollowerCount:   userListRpc.Users[i].FollowerCount,
				IsFollow:        isFollowList[i],
				Avatar:          userListRpc.Users[i].Avatar,
				BackgroundImage: userListRpc.Users[i].Background,
				Signature:       userListRpc.Users[i].Signature,
				TotalFavorited:  userListRpc.Users[i].TotalFavorited,
				WorkCount:       userListRpc.Users[i].WorkCount,
				FavoriteCount:   userListRpc.Users[i].FavoriteCount,
			},
			PlayURL:       "https://840231514-1320167793.cos.ap-nanjing.myqcloud.com" + videoListRpc.Videos[i].PlayUrl,
			CoverURL:      "https://840231514-1320167793.cos.ap-nanjing.myqcloud.com" + videoListRpc.Videos[i].CoverUrl,
			FavoriteCount: videoListRpc.Videos[i].FavoriteCount,
			CommentCount:  videoListRpc.Videos[i].CommentCount,
			IsFavorite:    isFavoriteList[i],
			Title:         videoListRpc.Videos[i].Title,
		})
	}

	resp.StatusCode = 0
	resp.StatusMsg = "OK"
	c.JSON(consts.StatusOK, resp)
}
