/*
 * @Author: LIKE_A_STAR
 * @Date: 2023-11-24 22:27:04
 * @LastEditors: LIKE_A_STAR
 * @LastEditTime: 2024-02-18 19:18:52
 * @Description:
 * @FilePath: \vscode programd:\vscode\goWorker\src\douyin\internal\hertz-server\router\video_api\middleware.go
 */
// Code generated by hertz generator.

package video_api

import (
	"douyin/internal/pkg/logger/hertz_log"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{hertz_log.AccessLog()}
}

func _feedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _feed0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _list0Mw() []app.HandlerFunc {
	// your code...
	return nil
}
