// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	comment_api "douyin/hertz-server/router/comment_api"
	favorite_api "douyin/hertz-server/router/favorite_api"
	follow_api "douyin/hertz-server/router/follow_api"
	user_api "douyin/hertz-server/router/user_api"
	video_api "douyin/hertz-server/router/video_api"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	follow_api.Register(r)

	comment_api.Register(r)

	favorite_api.Register(r)

	video_api.Register(r)

	user_api.Register(r)
}
